### ISSUE TITLE
Running torizoncore-builder deploy fails with socket error

### ISSUE THREAD

**Issue by philippstucki** [torizon/torizoncore-builder#2]
When running  `torizoncore-builder deploy --remote-host 192.168.88.34 --remote-username torizon --remote-password torizon` it fails with the error below. Running `torizoncore-builder ostree serve` though works flawlessly.

Any hints in how to make this work?

```
Pulling OSTree with ref base (checksum 73027a4eb65448372b5b82ff27ce0168760f2ecf65c71ac2e3e28dfb9c21b3bb) from local archive repository...
Starting http server to serve OSTree.
An unexpected Exception occured. Please provide the following stack trace to
the Toradex TorizonCore support team:


Traceback (most recent call last):
  File "/builder/torizoncore-builder", line 217, in <module>
    mainargs.func(mainargs)
  File "/builder/tcbuilder/cli/deploy.py", line 101, in do_deploy
    do_deploy_ostree_remote(args)
  File "/builder/tcbuilder/cli/deploy.py", line 92, in do_deploy_ostree_remote
    dbe.deploy_ostree_remote(args.remote_host, args.remote_username,
  File "/builder/tcbuilder/backend/deploy.py", line 281, in deploy_ostree_remote
    http_server_thread = ostree.serve_ostree_start(src_ostree_archive_dir,
  File "/builder/tcbuilder/backend/ostree.py", line 344, in serve_ostree_start
    http_thread = HTTPThread(ostree_dir, host, port)
  File "/builder/tcbuilder/backend/ostree.py", line 323, in __init__
    self.http_server = HTTPServer((host, port), handler_init)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by philippstucki** [comment]
Turns out a misconfigured (empty) /etc/hosts on the host was causing this. After adding the line `127.0.0.1       localhost` deploying w. ssh works.
